repo:
  public: ruby-eventsource

publications:
  - url: https://rubygems.org/gems/ld-eventsource
    description: RubyGems
  - url: https://www.rubydoc.info/gems/ld-eventsource
    description: documentation

template:
  name: ruby
